Update TfL Image Processing tutorial
quixai/quix-docs pull request #178
Opened 2023-07-05 11:45 UTC by SteveRosam

2023-07-05 13:12 UTC, tbedford requested changes
Typo, plus the numbering seems to have gone slightly wrong:

![image](https://github.com/quixio/quix-docs/assets/25511700/6add60ac-9f9e-42be-a3b6-ecac51ecc54b)

This is also true for the **stream merge** topic, which is 6 in TOC but showing as 5 in topic.

2023-07-05 13:12 UTC, tbedford commented on docs/platform/tutorials/image-processing/index.md
> +    - Merge the seperate data streams into one
Typo. Separate.

2023-07-05 14:58 UTC, SteveRosam commented on docs/platform/tutorials/image-processing/index.md
> +    - Merge the seperate data streams into one
done and done

2023-07-05 16:09 UTC, SteveRosam commented
@tbedford this is ready for round 2

2023-07-06 08:11 UTC, tbedford approved these changes
LGTM

2023-07-06 08:35 UTC, merged