[add] - Added Qdrants' overview.md
quixai/quix-docs pull request #356
Opened 2024-05-23 16:50 UTC by jackquix

## Description

Qdrant's overview has been added, a code explanation is still required

* [GitHub issue](link) - link to GitHub issue (if there is one)

## Review

Proofread the text and check the links

* [Page to review](link)

2024-05-23 19:33 UTC, tbedford requested changes
* The PR description says "Qdrant, Weaviate, Upstash", but I only see Qdrant. 
* The `mkdocs.yml` file hasn;t been updated to include this, so they currently do not appear in the nav.

2024-05-23 19:33 UTC, tbedford commented on docs/integrations/vector-databases/qdrant/overview.md
> +search:
This isn't required.

2024-05-23 19:33 UTC, tbedford commented on docs/integrations/vector-databases/overview.md
> +search:
This isn't required.

2024-05-23 19:33 UTC, tbedford commented on docs/integrations/vector-databases/qdrant/overview.md
> +A template sink connector for Qdrant VectorDB can be found [here](https://github.com/quixio/template-continuous-vector-ingestion/tree/main/Ingest%20to%20Qdrant%20VectorDB). There is also a connector
External links should always use `{target=_blank}`.

2024-05-24 09:23 UTC, jackquix commented
> * The PR description says "Qdrant, Weaviate, Upstash", but I only see Qdrant.
> 
>     * The `mkdocs.yml` file hasn;t been updated to include this, so they currently do not appear in the nav.

I'm commiting one document at a time and I'll submit the PR once they're all added to the PR. Feel free to help me improve this work flow

2024-05-24 09:24 UTC, jackquix commented on docs/integrations/vector-databases/qdrant/overview.md
> +search:
Why isn't it? What does this do?

2024-05-24 09:30 UTC, tbedford commented on docs/integrations/vector-databases/qdrant/overview.md
> +search:
It causes the page to rank higher in search, which is not required for this page. It's only used for very specific pages we want to boost.

2024-05-24 09:33 UTC, tbedford commented on docs/integrations/vector-databases/qdrant/overview.md
> +search:
Also, I just notice you have two capitalizations of Qdrant - in the description you use "QDrant" which is not correct from brief check of their website.

2024-05-24 09:36 UTC, tbedford commented
> I'm commiting one document at a time and I'll submit the PR once they're all added to the PR. Feel free to help me improve this work flow

The normal workflow would be to add a reviewer when you're happy with the PR. This saves time, as there's no point getting a review done if you're then going to add more files, as the review would need to be done again. Thanks.

2024-05-24 09:47 UTC, jackquix commented
> > I'm commiting one document at a time and I'll submit the PR once they're all added to the PR. Feel free to help me improve this work flow
> 
> The normal workflow would be to add a reviewer when you're happy with the PR. This saves time, as there's no point getting a review done if you're then going to add more files, as the review would need to be done again. Thanks.

But the work flow of commit commit commit to a PR is okay?

2024-05-24 09:48 UTC, tbedford commented
> But the work flow of commit commit commit to a PR is okay?

Yes.

2024-05-24 14:07 UTC, jackquix commented
I expect the Upstash and Weaviate overviews to be updated when the people from those companies get back to me. Hopefully early next week. Otherwise I will just merge

2024-05-24 14:34 UTC, tbedford requested changes
Some serious issues. Please do not merge. 

See comments, also screenshot:

![image](https://github.com/quixio/quix-docs/assets/25511700/9c1e5a29-bb3a-483b-a305-5cb38eedb09e)

2024-05-24 14:34 UTC, tbedford commented on docs/integrations/vector-databases/overview.md
> +search:
search metadata is still here.

2024-05-24 14:34 UTC, tbedford commented on docs/integrations/vector-databases/upstash/overview.md
> +---
You need a blank line after the `---` and the heading.

2024-05-24 14:34 UTC, tbedford commented on docs/integrations/vector-databases/overview.md
> +## Overview - Vector Databases
For some reason you've done the headings here as `##` they should be `#` for the top level heading.

2024-05-24 14:34 UTC, tbedford commented on mkdocs.yml
> +        - 'docs/integrations/vector-databases/qdrant/overview.md'
The link here is wrong:

'docs/integrations/vector-databases/qdrant/overview.md'

It should be 

'integrations/vector-databases/qdrant/overview.md'

2024-05-24 14:34 UTC, tbedford commented on mkdocs.yml
> +      - 'Upstash':
This is wrong, it's the entry for Upstash but you link to the Qdrant file.

2024-05-28 14:04 UTC, tbedford approved these changes
LGTM

2024-05-28 14:04 UTC, merged