Fix links
quixai/quix-docs pull request #45
Opened 2023-01-04 15:09 UTC by srosam

2023-01-10 11:33 UTC, SteveRosam commented
@tbedford According to my link checker there are no more broken links.

![image](https://user-images.githubusercontent.com/100689438/211541331-5b234bae-5fbf-40f3-9fc0-ccad7322cf3a.png)

2023-01-10 11:33 UTC, SteveRosam commented
I fixed the one we discussed

2023-01-10 11:39 UTC, tbedford requested changes
**Partial review only**

I've only checked a fraction of the files, but found some links that did not work for me. I thought I would submit an initial review though before I check too many files. Thanks.

I also have not checked any links in the SDK section.

2023-01-10 11:39 UTC, tbedford commented on docs/platform/how-to/use-sdk-token.md
> +primary intended use is to be used with the [SDK QuixStreamingClient](./sdk/connect#using-quixstreamingclient).
This link doesn't work.

2023-01-10 11:39 UTC, tbedford commented on docs/apis/data-catalogue-api/aggregate-tags.md
> +    Library](../../../platform/samples/samples) to set some up.
This link doesn't work.

2023-01-10 11:39 UTC, tbedford commented on docs/apis/data-catalogue-api/aggregate-time.md
> +    Library](../../../platform/samples/samples) to set some up.
This link doesn't work.

2023-01-10 11:39 UTC, tbedford commented on docs/apis/data-catalogue-api/filter-tags.md
> +    Library](../../../platform/samples/samples) to set some up.
This link doesn't work.

2023-01-10 11:39 UTC, tbedford commented on docs/apis/data-catalogue-api/get-swagger.md
> +id](../../../platform/how-to/get-workspace-id), or follow these instructions:
This link doesn't work.

2023-01-10 11:39 UTC, tbedford commented on docs/apis/data-catalogue-api/intro.md
> +use to be meaningful. You can use any Source of our [Quix Library](../../../platform/samples/samples.html) to do this using the Quix
This link doesn't work.

2023-01-10 11:39 UTC, tbedford commented on docs/apis/data-catalogue-api/raw-data.md
> +    Library](../../../platform/samples/samples) to set some up.
This link doesn't work.

2023-01-10 11:39 UTC, tbedford commented on docs/apis/data-catalogue-api/streams-filtered.md
> +    Library](../../../platform/samples/samples) to set some up.
This link doesn't work.

2023-01-10 11:39 UTC, tbedford commented on docs/apis/data-catalogue-api/streams-models.md
> +    Library](../../../platform/samples/samples) to set some up.
This link doesn't work.

2023-01-10 11:39 UTC, tbedford commented on docs/apis/data-catalogue-api/streams-paged.md
> +    Library](../../../platform/samples/samples) to set some up.
This link doesn't work.

2023-01-10 11:39 UTC, tbedford commented on docs/apis/data-catalogue-api/streams-paged.md
> +[workspace](../../../platform/definitions#workspace), across
This link doesn't work.

2023-01-10 11:39 UTC, tbedford commented on docs/apis/data-catalogue-api/streams-paged.md
> +[topics](../../../platform/definitions#topics) and locations, with a
This link doesn't work.

2023-01-10 12:25 UTC, SteveRosam commented
@tbedford those should be fixed

2023-01-10 12:37 UTC, tbedford requested changes
**Partial Review**

Broken links noted.

2023-01-10 12:37 UTC, tbedford commented on docs/apis/data-catalogue-api/aggregate-tags.md
> +    Library](../../../platform/samples/samples.html) to set some up.
This link does not work.

2023-01-10 12:37 UTC, tbedford commented on docs/apis/data-catalogue-api/aggregate-time.md
> +    Library](../../../platform/samples/samples.html) to set some up.
This link does not work.

2023-01-10 12:37 UTC, tbedford commented on docs/apis/data-catalogue-api/filter-tags.md
> +    Library](../../../platform/samples/samples.html) to set some up.
This link does not work.

2023-01-10 12:37 UTC, tbedford commented on docs/apis/data-catalogue-api/raw-data.md
> +    Library](../../../platform/samples/samples.html) to set some up.
This link does not work.

2023-01-10 12:37 UTC, tbedford commented on docs/apis/data-catalogue-api/streams-filtered.md
> +    Library](../../../platform/samples/samples.html) to set some up.
This link does not work.

2023-01-10 12:37 UTC, tbedford commented on docs/apis/data-catalogue-api/streams-models.md
> +    Library](../../../platform/samples/samples.html) to set some up.
This link does not work.

2023-01-10 12:37 UTC, tbedford commented on docs/apis/data-catalogue-api/streams-paged.md
> +[workspace](../../../platform/definitions.html#workspace), across
This link does not work.

2023-01-10 14:28 UTC, tbedford requested changes
**Partial review**

Getting there!

I've seen a number of links out a level. For example:

* ../../../platform/definitions.html#workspace
* ../../../platform/definitions.html#topics

Which I think should be:

* ../../platform/definitions.html#workspace
* ../../platform/definitions.html#topics

2023-01-10 14:28 UTC, tbedford commented on docs/apis/data-catalogue-api/streams-paged.md
> +[workspace](../../../platform/definitions.html#workspace), across
Should be `../../platform/definitions.html#workspace`

2023-01-10 14:28 UTC, tbedford commented on docs/apis/data-catalogue-api/streams-paged.md
> +[topics](../../../platform/definitions.html#topics) and locations, with a
Should be `../../platform/definitions.html#topics`

2023-01-10 14:28 UTC, tbedford commented on docs/apis/streaming-writer-api/create-stream.md
> +the [Topic](../../../platform/definitions.html#topics) you wish to create the
Should be `../../platform/definitions.html#topics`

2023-01-10 14:28 UTC, tbedford commented on docs/apis/streaming-writer-api/create-stream.md
> +  - You should have a [Workspace set up](../../../platform/definitions.html#workspace) with at least one [Topic](../../../platform/definitions.html#topics).
Should be `../../platform/definitions.html#workspace` and `../../platform/definitions.html#topics`.

2023-01-10 14:28 UTC, tbedford commented on docs/apis/streaming-writer-api/get-swagger.md
> +To determine the final URL, you can [find out how to get a workspace id](../../../platform/how-to/get-workspace-id.html), or follow these
Should be `../../platform/how-to/get-workspace-id.html`

2023-01-10 14:28 UTC, tbedford commented on docs/apis/streaming-writer-api/send-data.md
> +  - You should have a [Workspace set up](../../../platform/definitions.html#workspace) with at least one [Topic](../../../platform/definitions.html#topics).
Should be `../../platform/definitions.html#workspace`

2023-01-11 11:17 UTC, tbedford requested changes
**Full review**

I think I have now gone through every changed file in this PR.

2023-01-11 11:17 UTC, tbedford commented on docs/index.md
> +    [:octicons-arrow-right-24: Sentiment Analysis](./platform/tutorials/sentiment-analysis/)
Was working, but this change won't work. Because it's at top level `./platform/tutorials/sentiment-analysis/index.html` will work though.

2023-01-11 11:17 UTC, tbedford commented on docs/index.md
> +    [:octicons-arrow-right-24: Image Processing](./platform/tutorials/imageProcessing/)
As previous comment this link change won't work. `./platform/tutorials/imageProcessing/imageProcessing.html` will work.

2023-01-11 11:17 UTC, tbedford commented on docs/platform/tutorials/currency-alerting/currency-alerting.md
> +* :purple_square: Transformation — implements the processing of data, for example, cleaning data or implementing a Machine Learning (ML) model.
Something not right here: 

![image](https://user-images.githubusercontent.com/25511700/211788415-fa635a1e-32c7-4bae-959f-675e0f2ef7e8.png)

2023-01-11 15:48 UTC, tbedford approved these changes
LGTM!

2023-01-11 16:05 UTC, merged