First cut of event detection tutorial
quixai/quix-docs pull request #60
Opened 2023-01-20 16:25 UTC by srosam

2023-02-10 13:15 UTC, SteveRosam commented
@tbedford if you have time and want to run through this you could

2023-02-10 14:24 UTC, tbedford requested changes
Looks good! A few minor comments related to conforming with style guide. 

Mostly, I only commented on the first instance of an issue, but should be easy to find the others.

This review is a copy edit review only. I've not yet gone through the steps.

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +	Next add these lines which will download the pkl file (the pre trained model) from our storage account and load the model into memory.
https://www.merriam-webster.com/dictionary/pretrain -> pretrained

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +In reality our ML model was trained to detect the difference between a phone being shaken vs just being used normally. You actually don’t have to use an ML model at all! There are various ways this s
"vs" -> versus.
"for example, we could simply" -> for example, you could detect (because they might be under the impression it's something Quix can detect for them.)

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +## Skeleton service
Can we if possible change this to be something like "minimal service" or "basic service"?

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +1. Navigate to the library and search for `Empty template - Transformation`
All step sentences should be terminated with a period. Other instances below.

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +1. Open the `requirements.txt` file and add the following lines to ensure all the packages are installed
Terminate line with colon before breaks for code and images. Also other instances below.

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +	Next add these lines which will download the pkl file (the pre trained model) from our storage account and load the model into memory.
"download the pkl file " - should that be PKL file, or perhaps `.pkl` file?

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +5. Locate the line that instantiates the `QuixFunction` and pass the `loaded_model` as the last parameter. 	The QuixFunction class will use this to predict crash events.
> last parameter. 	The QuixFunction

There are erroneous spaces in there after the period.

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +    ```py
Indentation looks off here. Also after the colon, before the codeblock, always have a blank line.

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +	```py
> triple backticks py

Don't we usually use triple backticks _python_? I've not checked yet whether than causes an issue with the syntax highlighter or not. Probably OK, but thought I would raise as we seem to have consistently used _python_ elsewhere. Thanks.

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +4. If you went for the CSV data then wait for a crash event to be streamed from the data set or stop and start the service in another browser tab
> If you went for the CSV data...

Better as chose (or selected) the CSV data...

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +4. If you went for the CSV data then wait for a crash event to be streamed from the data set or stop and start the service in another browser tab
> from the data set or stop and start

from the data set, or stop and start

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +4. On the `Messages` tab select `output : phone-out` from the first drop down
> from the first drop down

Drop-down as per Microsoft and also [here](https://en.wikipedia.org/wiki/Drop-down_list). Also, other instances below.

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +5. Gently shake your phone, or wait for another crash event from the CSV data, and observe that crash events are streamed to the output topic. You can click these rows to investigate the event data e
e.g. -> for example, as per writing style guide. Also, other instances below.

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +In the next part, deploy the demos '[Crash detection UI](crashDetectionUI.md)'
In other tutorials you used a nice arrangement like:

```
[Deploy the first part of the solution by following step 1 :material-arrow-right-circle:{ align=right }](sentiment-demo-ui.md)
```

I think that format for the "next step" is quite nice and we should apply it consistently as we update tutorials. This comment also applies to other instances below.

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/crashDetectionUI.md
> +# 3. Demo UI
> docs/platform/tutorials/eventDetection/crashDetectionUI.md

I thought we were going to use skewer/kebab case for all file names?

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/dataAcquisition.md
> +2. Stream pre recorded [CSV data](#csv-data)
> pre recorded

Prerecorded as per https://www.merriam-webster.com/dictionary/prerecorded

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/dataAcquisition.md
> +An external source is a representation of a data source that is external to Quix, e.g. an IoT device or a service that is pushing data to a Quix topic via one of our API's.
> service that is pushing data to a Quix topic via one of our API's.

APIs. 
Minor: via -> using.

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/dataAcquisition.md
> +If you don’t have an Android device or you’d rather just stream some data we’ve provided then this is the data source for you!
> If you don’t have an Android device or you’d rather just stream some data we’ve provided then this is the data source for you! 

If you don’t have an Android device, or you’d rather stream some data provided for you, then use this data source.

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/dataAcquisition.md
> +7. Open the requirements.txt file and add `urllib3` to a new line
> Open the requirements.txt file

requirements.txt should be in backticks.

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/index.md
> +You will deploy a crash detection service to detect crashes in real-time and a UI to view the location of the incident.
> in real-time and a UI to view 

Only hyphenated for adjective, so in this case real time.

2023-02-10 14:24 UTC, tbedford commented on docs/platform/tutorials/eventDetection/index.md
> +In this example the actual crash detection is performed using an ML model, pre trained with data from Quix. We have a tutorial that shows you how to train a basic model with a small subset of data, y
> pre trained with data

Pretrained.

2023-02-13 14:07 UTC, tbedford commented on docs/platform/tutorials/eventDetection/dataAcquisition.md
> +	???- info "Your data should look like this"
Mine didn't look like that. On investigation it turns out that the messages can have a different format - for example, some have geolocation data and some don't. We should just add a note that the message format can vary one one message to the next.

2023-02-28 13:46 UTC, SteveRosam commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +1. Navigate to the library and search for `Empty template - Transformation`
hmm.. i was going for all steps without a period.. but as long as its consistent.

2023-02-28 13:51 UTC, SteveRosam commented on docs/platform/tutorials/eventDetection/crashDetection.md
> +	```py
i always use py

2023-02-28 14:18 UTC, SteveRosam commented on docs/platform/tutorials/eventDetection/dataAcquisition.md
> +If you don’t have an Android device or you’d rather just stream some data we’ve provided then this is the data source for you!
We cant inject personality into these?

2023-02-28 14:51 UTC, tbedford commented on docs/platform/tutorials/eventDetection/dataAcquisition.md
> +If you don’t have an Android device or you’d rather just stream some data we’ve provided then this is the data source for you!
In the blog, absolutely. For dev docs I always have an eye on translation and/or developers whose first language is not English - keeping it simple and directive, and as easy as possible to read: You want this...do this. Just a suggestion though.

2023-02-28 15:09 UTC, SteveRosam commented
@tbedford I have added a section telling the reader to update the dockerfile. This fixes the issues encountered when deploy the crash detection service.

Also sorted all of the review comments so far.

2023-02-28 16:06 UTC, tbedford submitted a review, later dismissed
Tested with modified dockerfile and LGTM!

2023-03-06 10:49 UTC, merged