Public services "how-to"
quixai/quix-docs pull request #79
Opened 2023-02-23 17:10 UTC by srosam

2023-02-24 16:38 UTC, tbedford requested changes
Minor comments.

2023-02-24 16:38 UTC, tbedford commented on docs/platform/how-to/deploy-public-page.md
> +The Quix SaaS platform allows you to deploy public facing web pages and API's.
API's -> APIs.
public facing -> public-facing.
Can we extend the first paragraph to explain what this How-To will help the user achieve.

2023-02-24 16:38 UTC, tbedford commented on docs/platform/how-to/deploy-public-page.md
> +# Public services
Should we make the title more active, for example, "Deploying public services" or perhaps "How to deploy a public service"?

2023-02-24 16:38 UTC, tbedford commented on docs/platform/how-to/deploy-public-page.md
> +In our Library you can find our `Web API Template` which demonstrates how to create a API using `Node`.
Should Node be in backticks? Node.js.

2023-02-24 16:38 UTC, tbedford commented on docs/platform/how-to/deploy-public-page.md
> + - Node JS which can be used to host Dash apps and any Javascript based websites:
"Node JS" -> Node.js
Javascript -> JavaScript.
JavaScript-based.

What are Dash apps? Do we need to provide a link?

2023-02-24 16:38 UTC, tbedford commented on docs/platform/how-to/deploy-public-page.md
> +1. Switch on `Public Access`
Terminate with period.

2023-02-24 16:38 UTC, tbedford commented on docs/platform/how-to/deploy-public-page.md
> +We advise that you build in a security layer to ensure your data is secure and only the intended recipients have access to it.
> We advise that you build

Quix advises you to build...

2023-02-24 16:38 UTC, tbedford commented on docs/platform/how-to/deploy-public-page.md
> +Fid out more [here](https://auth0.com/blog/complete-guide-to-angular-user-authentication/){target="_blank"}, if you're interested in securing an Angular application.
Fid -> Find.

2023-02-28 15:44 UTC, SteveRosam commented
@tbedford updated based on your comments.

2023-02-28 16:09 UTC, tbedford approved these changes
LGTM!

2023-03-01 13:04 UTC, merged